### ISSUE TITLE
help

### ISSUE THREAD

**Issue by cq70605** [bobo0810/XueLangTianchi#1]
你好，请问这个模型测试结果准确率多少？

**Comment by bobo0810** [comment]
你好，我仅仅是构建了一个YOLO V1最初的版本，测试了几张图片，结果并不是很好。如果可以进复赛，我将重点提高YOLO v1的准确率。

**Comment by cq70605** [comment]
请问你目前是把它考虑成分类问题还是检测问题呢？ 我用vgg16做分类，原图只做了翻转来增广，只有76+...

**Comment by bobo0810** [comment]
YOLO v1版本是作为目标检测，所以只使用了带有xml标注的数据。我现在是用分类，只做到线上0.85

**Comment by cq70605** [comment]
第一次参加比赛，抱着学习的心态。 可以加个联系方式嘛 q：506456912

**Comment by bobo0810** [comment]
同学你好，我也是第一次参加比赛的菜鸡...我可能还没你知道得多

**Comment by KingHxg** [comment]
您好 请问您现在是做的检测是吗 没有做分类是吗 方便加个qq吗 793480528 向您学习下

**Comment by bobo0810** [comment]
@KingHxg 
初赛估计用不到检测，我一直在做分类，各种方法都试试。我只是个菜鸡...

**Comment by KingHxg** [comment]
@bobo0810 感谢您的回复 方便加个qq吗 我是初出茅庐的小菜鸟 想向您请教下 您不要误会  我没有要剽窃您的作品的意思 只是单纯的请教知识  我只是把这个比赛当作一个项目来学习 参赛的话 水平达不到啦
