### ISSUE TITLE
数据集解压出来没有test文件。

### ISSUE THREAD

**Issue by LangYa1945** [bobo0810/XueLangTianchi#2]
你好，我从百度云盘里下载的数据没有下面两个数据文件，这两个在哪里呀
─xuelang_round1_test_a_20180709
│
└───xuelang_round1_test_b

**Comment by bobo0810** [comment]
对于初赛，选手只拿到图片，并没有对应真值。选手在本地通过test_a、test_b的图片生成csv，将csv提交到天池获得分数。

**Comment by bobo0810** [comment]
@LangYa1945
